# Generated by Django 2.2.16 on 2023-08-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentHockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('tournament_stage_type', models.TextField(null=True)),
                ('tournament_imng', models.TextField(null=True)),
                ('TOURNAMENT_TEMPLATE_ID', models.TextField(null=True)),
                ('TOURNAMENT_IMAGE', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HockeyLiveEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_ID', models.TextField(null=True)),
                ('START_TIME', models.TextField(null=True)),
                ('START_UTIME', models.TextField(null=True)),
                ('STAGE_TYPE', models.TextField(null=True)),
                ('MERGE_STAGE_TYPE', models.TextField(null=True)),
                ('STAGE', models.TextField(null=True)),
                ('SORT', models.TextField(null=True)),
                ('LIVE_MARK', models.TextField(null=True)),
                ('HAS_LINEPS', models.TextField(null=True)),
                ('STAGE_START_TIME', models.TextField(null=True)),
                ('GAME_TIME', models.TextField(null=True)),
                ('PLAYING_ON_SETS', models.TextField(null=True)),
                ('RECENT_OVERS', models.TextField(null=True)),
                ('SHORTNAME_HOME', models.TextField(null=True)),
                ('HOME_PARTICIPANT_IDS', models.TextField(null=True)),
                ('HOME_PARTICIPANT_TYPES', models.TextField(null=True)),
                ('HOME_NAME', models.TextField(null=True)),
                ('HOME_PARTICIPANT_NAME_ONE', models.TextField(null=True)),
                ('HOME_EVENT_PARTICIPANT_ID', models.TextField(null=True)),
                ('HOME_GOAL_VAR', models.TextField(null=True)),
                ('HOME_SCORE_CURRENT', models.TextField(null=True)),
                ('HOME_SCORE_PART_1', models.TextField(null=True)),
                ('HOME_SCORE_PART_2', models.TextField(null=True)),
                ('HOME_SCORE_PART_3', models.TextField(null=True)),
                ('HOME_IMAGES', models.TextField(null=True)),
                ('SHORTNAME_AWAY', models.TextField(null=True)),
                ('AWAY_PARTICIPANT_IDS', models.TextField(null=True)),
                ('AWAY_PARTICIPANT_TYPES', models.TextField(null=True)),
                ('AWAY_NAME', models.TextField(null=True)),
                ('AWAY_PARTICIPANT_NAME_ONE', models.TextField(null=True)),
                ('AWAY_EVENT_PARTICIPANT_ID', models.TextField(null=True)),
                ('AWAY_GOAL_VAR', models.TextField(null=True)),
                ('AWAY_SCORE_CURRENT', models.TextField(null=True)),
                ('AWAY_SCORE_FULL', models.TextField(null=True)),
                ('AWAY_SCORE_PART_1', models.TextField(null=True)),
                ('AWAY_SCORE_PART_2', models.TextField(null=True)),
                ('AWAY_SCORE_PART_3', models.TextField(null=True)),
                ('AWAY_IMAGES', models.TextField(null=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_hockey', to='scoreflash.TournamentHockey')),
            ],
        ),
    ]
