# Generated by Django 2.2.16 on 2023-08-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
