# Generated by Django 2.2.16 on 2023-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='away_images',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='home_images',
            field=models.TextField(null=True),
        ),
    ]
