# Generated by Django 2.2.16 on 2023-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0002_auto_20230811_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='start_utime',
            field=models.TimeField(null=True),
        ),
    ]
