# Generated by Django 3.1.10 on 2023-09-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0002_hockeyliveevents_tournamenthockey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='market',
            name='bookmaker',
        ),
        migrations.RemoveField(
            model_name='match',
            name='betting_type',
        ),
        migrations.RemoveField(
            model_name='numberofsportevents',
            name='sport_id',
        ),
        migrations.RemoveField(
            model_name='period',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='sport_id',
        ),
        migrations.DeleteModel(
            name='BettingType',
        ),
        migrations.DeleteModel(
            name='Bookmaker',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='NumberOfSportEvents',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
