# Generated by Django 2.2.16 on 2023-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0003_events_start_utime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_utime',
            field=models.TextField(null=True),
        ),
    ]
