# Generated by Django 2.2.16 on 2023-08-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0004_auto_20230811_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scoreflash.Tournament'),
        ),
    ]
