# Generated by Django 3.1.10 on 2023-09-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0004_allhockey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllHockey',
        ),
    ]
