# Generated by Django 2.2.16 on 2023-07-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0006_auto_20230729_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_event_id', models.TextField(null=True)),
            ],
        ),
    ]
