# Generated by Django 3.1.10 on 2023-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0006_allhockey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledHockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.TextField(null=True)),
                ('tournament_stage_type', models.TextField(null=True)),
                ('tournament_imng', models.TextField(null=True)),
                ('event_id', models.TextField(null=True)),
                ('start_time', models.TextField(null=True)),
                ('start_utime', models.TextField(null=True)),
                ('shortname_home', models.TextField(null=True)),
                ('home_name', models.TextField(null=True)),
                ('home_images', models.TextField(null=True)),
                ('shortname_away', models.TextField(null=True)),
                ('name_away', models.TextField(null=True)),
                ('away_images', models.TextField(null=True)),
            ],
        ),
    ]
