# Generated by Django 2.2.16 on 2023-08-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0006_tournament_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='event',
        ),
    ]
