# Generated by Django 2.2.16 on 2023-08-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0007_remove_tournament_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='away_images',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='home_images',
            field=models.URLField(null=True),
        ),
    ]
