# Generated by Django 3.1.10 on 2023-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0007_scheduledhockey'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndedHockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_stage_type', models.TextField(null=True)),
                ('tournament_imng', models.TextField(null=True)),
                ('event_id', models.TextField(null=True)),
                ('stage_tyoe', models.TextField(null=True)),
                ('round', models.TextField(null=True)),
                ('shortname_home', models.TextField(null=True)),
                ('home_name', models.TextField(null=True)),
                ('home_score_current', models.TextField(null=True)),
                ('home_score_part_1', models.TextField(null=True)),
                ('home_score_part_2', models.TextField(null=True)),
                ('home_score_part_3', models.TextField(null=True)),
                ('home_images', models.TextField(null=True)),
                ('shortname_away', models.TextField(null=True)),
                ('name_away', models.TextField(null=True)),
                ('away_score_current', models.TextField(null=True)),
                ('away_score_full', models.TextField(null=True)),
                ('away_score_part_1', models.TextField(null=True)),
                ('away_score_part_2', models.TextField(null=True)),
                ('away_score_part_3', models.TextField(null=True)),
                ('away_images', models.TextField(null=True)),
            ],
        ),
    ]
