# Generated by Django 2.2.16 on 2023-08-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0008_auto_20230809_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('tournament_stage_type', models.TextField(null=True)),
                ('tournament_imng', models.TextField(null=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreflash.Events')),
            ],
        ),
    ]
