# Generated by Django 3.1.10 on 2023-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0008_endedhockey'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='red_cards_away',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='red_cards_home',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='yellow_cards_away',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='yellow_cards_home',
            field=models.TextField(null=True),
        ),
    ]
