# Generated by Django 3.1.10 on 2023-09-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0010_auto_20230915_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventid',
            name='live_event_id',
            field=models.TextField(null=True),
        ),
    ]
