# Generated by Django 3.1.10 on 2023-09-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreflash', '0012_auto_20230919_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hockeyliveevents',
            old_name='START_TIME',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='hockeyliveevents',
            old_name='START_UTIME',
            new_name='start_utime',
        ),
    ]
